name: dogu-actions/prepare
description: prepare run test
author: dogu
inputs:
  appVersion:
    description: app version to download and install
    default: ''
    required: false
  appPackageName:
    description: app package name to download and install
    default: ''
    required: false
  branch:
    description: branch to checkout. if tag is set, branch is ignored.
    default: main
    required: false
  tag:
    description: tag to checkout. if tag is set, branch is ignored.
    default: ''
    required: false
  clean:
    description: run git clean -fdx before git pull without git clone
    default: true
    required: false
  checkoutPath:
    description: relative path of Dogu routine workspace path or absolute path to checkout
    default: ''
    required: false
  checkoutUrl:
    description: checkout url. if not set, use repository url from Dogu project settings. recommended to use repository url from Dogu project settings.
    default: ''
    required: false
  uninstallApp:
    description: uninstall app before install
    default: false
    required: false
  gamiumEnginePort:
    description: gamium engine port
    default: 50061
    required: false
  retryCount:
    description: retry count to gamium engine connection
    default: 2
    required: false
  retryInterval:
    description: retry interval to gamium engine connection
    default: 1000
    required: false
  requestTimeout:
    description: request timeout
    default: 50000
    required: false
runs:
  main: build/src/main.js
