export const REMOTE_DEVICE_JOB_TABLE_NAME = 'remote_device_job';

export enum REMOTE_DEVICE_JOB_STATE {
  UNSPECIFIED = 0,
  WAITING = 1,
  IN_PROGRESS = 2,
  CANCEL_REQUESTED = 3,
  SUCCESS = 4,
  FAILURE = 5,
  CANCELLED = 6,
  SKIPPED = 7,
}

export enum REMOTE_DEVICE_JOB_SESSION_STATE {
  UNSPECIFIED = 0,
  WAITING = 1,
  IN_PROGRESS = 2,
  COMPLETE = 3,
  FAILURE = 4,
}
