# Dependabot
- name: dependencies
  color: "ffffff"
  description: Pull requests that update a dependency file

# first issue
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

# Status
- name: "status: needs triage"
  color: "BC39CC"
  description: Needs to be triaged
- name: "status: in progress"
  color: "BC39CC"
  description: Working in progress
- name: "status: needs more information"
  color: "BC39CC"
  description: "Lack of information"
- name: "status: accepting pr"
  color: "BC39CC"
  description: "Issue accepted, waiting for PR"
- name: "status: blocked"
  color: "BC39CC"
  description: "Issue is blocked by other issue"
- name: "status: duplicate"
  color: "BC39CC"
  description: "This issue or pull request already exists"
- name: "status: wontfix"
  color: "BC39CC"
  description: "This will not be worked on"
- name: "status: invalid"
  color: "BC39CC"
  description: "This does not seem right"

# Issue type
- name: "type: bug"
  color: "B60205"
  description: ""
- name: "type: feature request"
  color: "B60205"
  description: ""
- name: "type: documentation"
  color: "B60205"
  description: ""

# Bug status
- name: "bug: reproducible"
  color: "d96c6c"
  description: ""
- name: "bug: not reproducible"
  color: "d96c6c"
  description: ""
- name: "bug: needs investigation"
  color: "d96c6c"
  description: ""

# OS
- name: "os: android"
  color: "006B75"
  description: ""
- name: "os: ios"
  color: "006B75"
  description: ""
- name: "os: windows"
  color: "006B75"
  description: ""
- name: "os: macos"
  color: "006B75"
  description: ""

# Platform
- name: "platform: apple"
  color: "FEF2C0"
  description: ""
- name: "platform: android"
  color: "FEF2C0"
  description: ""
- name: "platform: windows"
  color: "FEF2C0"
  description: ""
- name: "platform: unity"
  color: "FEF2C0"
  description: ""
- name: "platform: unreal"
  color: "FEF2C0"
  description: ""

# Hosting type
- name: "hosting: self-hosted"
  color: "FBCA04"
  description: ""
- name: "hosting: saas"
  color: "FBCA04"
  description: ""
