nodeLinker: pnp

packageExtensions:
  chalk@5.2.0:
    dependencies:
      '#ansi-styles': 'npm:ansi-styles@6.1.0'
      '#supports-color': 'npm:supports-color@9.2.2'
  eslint-config-next@*:
    dependencies:
      next: '*'
  next@*:
    dependencies:
      react: '*'
      react-dom: '*'
  recharts@*:
    peerDependencies:
      prop-types: '*'
  '@docusaurus/eslint-plugin@*':
    dependencies:
      eslint: '*'
  '@algolia/autocomplete-preset-algolia@*':
    dependencies:
      '@algolia/client-search': '*'
  '@algolia/autocomplete-shared@*':
    dependencies:
      'algoliasearch': '*'
      '@algolia/client-search': '*'
  '@algolia/autocomplete-plugin-algolia-insights@*':
    dependencies:
      'search-insights': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

pnpIgnorePatterns:
  - ./nm-space/**/*
  - ./third-party/**/*

yarnPath: .yarn/releases/yarn-3.3.1.cjs
