nodeLinker: pnp

packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: '*'
  next@*:
    dependencies:
      react: '*'
      react-dom: '*'
  recharts@*:
    peerDependencies:
      prop-types: '*'
  chalk@5.2.0:
    dependencies:
      '#ansi-styles': npm:ansi-styles@6.1.0
      '#supports-color': npm:supports-color@9.2.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs

pnpIgnorePatterns:
  - './nm-space/**/*'
  - './third-party/**/*'
