name: test pipeline hierarchy

on:
  workflow_dispatch:

jobs:
  checkout-user-project-script:
    runs-on:
      group: host
    steps:
      - name: checkout-user-project-script
        run: echo checkout user project script...

  # download-app:
  #   needs: checkout-user-project-script
  #   runs-on:
  #     group: host
  #   steps:
  #     - name: download-app
  #       run: echo download app...
  # uses: dogu-action/git-checkout
  # with:
  #   url: https://github.com/pluwen/apple-device-model-list.git
  #   destPath: $HOME/.dogu/repo/apple-device-model-list

  download-app:
    needs: checkout-user-project-script
    runs-on:
      group: host
    steps:
      - name: download-app
        run: echo download app...

  test-android:
    needs: download-app
    runs-on:
      group: android
    steps:
      - name: test-android
        run: yarn workspace gamium-client-userproject run run:DoguRpgSample
        env:
          DOGU_GAMIUM_APP_PATH: $HOME/.dogu/demo/android/**/dogurpgsample.apk
          DOGU_GAMIUM_PLATFORM: android # 'android' | 'ios' | 'windows' | 'macos' | 'linux'

  test-ios:
    needs: download-app
    runs-on:
      group: ios
    steps:
      - name: test-ios
        run: yarn workspace gamium-client-userproject run run:DoguRpgSample
        env:
          DOGU_GAMIUM_BUILD_DIRECTORYPATH: $HOME/.dogu/demo/ios
          DOGU_GAMIUM_BUILD_FILEPATH: '**/DoguRpgSample.ipa'
          DOGU_GAMIUM_PLATFORM: PLATFORM_IOS
