name: 15s timestamp

on:
  workflow_dispatch:

env:
  TEST_SCRIPT: test/room-based-game.ts

jobs:
  build:
    runs-on:
      group: adb
    steps:
      - name: 'clone project'
        run: 'for i in {1..20}; do timestamp=$(date +%s); json="{\"timestamp\": $timestamp}"; echo $json; sleep 1; done'

      - name: 'build project1'
        run: echo "타임스탬프 출력 시작..." ; start=$(date +%s) ; while [[ $(($(date +%s) - $start)) -lt 20 ]] ; do echo $(date +%s) ; sleep 1 ; done ; echo "타임스탬프 출력 종료."
