name: test recording

on:
  workflow_dispatch:

jobs:
  checkout-user-project-script:
    runs-on:
      group: test-tag
    steps:
      - name: checkout-user-project-script
        run: echo checkout user project script...
