name: test gamium

on:
  workflow_dispatch:

jobs:
  test-ios:
    runs-on:
      group: ios
    steps:
      - name: test-ios
        run: yarn workspace gamium-client-userproject run run:DoguRpgSample
        env:
          DOGU_GAMIUM_BUILD_DIRECTORYPATH: $HOME/.dogu/demo/ios
          DOGU_GAMIUM_BUILD_FILEPATH: '**/DoguRpgSample.ipa'
          DOGU_GAMIUM_PLATFORM: PLATFORM_IOS
