name: test log

on:
  workflow_dispatch:

env:
  A: AA

jobs:
  print-pipeline-env:
    runs-on:
      group: my-host-device
    steps:
      - name: print-pipeline-env
        uses: command
        with:
          command: printenv

  print-step-env:
    runs-on:
      group: my-host-device
    steps:
      - name: print-step-env
        uses: command
        with:
          command: printenv
        env:
          A: AAA

  do-something:
    runs-on:
      group: my-host-device
    steps:
      - name: checkout-something
        uses: CheckoutGit
        with:
          url: https://github.com/pluwen/apple-device-model-list.git
          destPath: $HOME/repo/dogu/.temp/apple-device-model-list

  # download-app:
  #   needs: checkout-gamium-script
  #   runs-on:
  #     group: my-host-device
  #   steps:
  #     - name: download-app
  #       uses: command
  #       with:
  #         command: echo
  #         args:
  #           - hello
  #           - world
