#      ㅁ
#    /    \
#  |        ㅁ
#  |     /    \
#  |   ㅁ       \
#  |  /           \
#  ㅁ               ㅁ
#  | \            /
#  |   ㅁ        /
#  |      \   /
#  |        ㅁ
#    \    /
#      ㅁ
#

name: template 4

on:
  workflow_dispatch:

env:
  TEST_SCRIPT: test/room-based-game.ts

jobs:
  JOB-1:
    runs-on:
      group: TEST_GROUP
    record: true
    steps:
      - name: STEP 1
        run: echo TEST template...

      - name: STEP 2
        run: echo TEST template...
  JOB-2:
    needs: JOB-1
    runs-on:
      group: TEST_GROUP
    record: true
    steps:
      - name: STEP 1
        run: echo TEST template...

      - name: STEP 2
        run: echo TEST template...
  JOB-3:
    needs: JOB-1
    runs-on:
      group: TEST_GROUP
    record: true
    steps:
      - name: STEP 1
        run: echo TEST template...

      - name: STEP 2
        run: echo TEST template...
  JOB-4:
    needs: JOB-1
    runs-on:
      group: TEST_GROUP
    record: true
    steps:
      - name: STEP 1
        run: echo TEST template...

      - name: STEP 2
        run: echo TEST template...
  JOB-5:
    needs: JOB-1
    runs-on:
      group: TEST_GROUP
    record: true
    steps:
      - name: STEP 1
        run: echo TEST template...

      - name: STEP 2
        run: echo TEST template...
  JOB-6:
    needs: [JOB-2, JOB-3]
    runs-on:
      group: TEST_GROUP
    record: true
    steps:
      - name: STEP 1
        run: echo TEST template...

      - name: STEP 2
        run: echo TEST template...
  JOB-7:
    needs: [JOB-4, JOB-5]
    runs-on:
      group: TEST_GROUP
    record: true
    steps:
      - name: STEP 1
        run: echo TEST template...

      - name: STEP 2
        run: echo TEST template...
  JOB-8:
    needs: [JOB-6, JOB-7]
    runs-on:
      group: TEST_GROUP
    record: true
    steps:
      - name: STEP 1
        run: echo TEST template...

      - name: STEP 2
        run: echo TEST template...
