#
# ㅁ - ㅁ - ㅁ- ㅁ
#

name: template 1

on:
  workflow_dispatch:

env:
  TEST_SCRIPT: test/room-based-game.ts

jobs:
  JOB-1:
    record: true
    runs-on:
      group: TEST_GROUP
    steps:
      - name: STEP 1
        run: echo TEST template...

      - name: STEP 2
        run: echo TEST template...
  JOB-2:
    needs: JOB-1
    record: true
    runs-on:
      group: TEST_GROUP
    steps:
      - name: STEP 1
        run: echo TEST template...

      - name: STEP 2
        run: echo TEST template...
  JOB-3:
    needs: JOB-2
    record: true
    runs-on:
      group: TEST_GROUP
    steps:
      - name: STEP 1
        run: echo TEST template...

      - name: STEP 2
        run: echo TEST template...
  JOB-4:
    needs: JOB-3
    record: true
    runs-on:
      group: TEST_GROUP
    steps:
      - name: STEP 1
        run: echo TEST template...

      - name: STEP 2
        run: echo TEST template...
