name: dogu-actions/checkout
description: checkout repository
author: dogu
inputs:
  branchOrTag:
    description: branch or tag to download
    default: main
    required: false
  clean:
    description: run git clean -fdx before git pull without git clone
    default: true
    required: false
  postCommand:
    description: command to run after checkout
    default: ''
    required: false
  checkoutPath:
    description: relative path of Dogu routine workspace path or absolute path to checkout
    default: ''
    required: false
  checkoutUrl:
    description: checkout url. if not set, use repository url from Dogu project settings. recommended to use repository url from Dogu project settings.
    default: ''
    required: false
runs:
  main: build/src/main.js
