export type ControllerHandlerId = number;

export const CONTROLLER_HANDLER_TABLE_NAME = 'controller_handler';

export const CONTROLLER_HANDLER_NAME_MIN_LENGTH = 1;
export const CONTROLLER_HANDLER_NAME_MAX_LENGTH = 45;
export const CONTROLLER_HANDLER_CONTOLLER_NAME_MIN_LENGTH = 1;
export const CONTROLLER_HANDLER_CONTOLLER_NAME_MAX_LENGTH = 45;
export const CONTROLLER_HANDLER_ACTION_NAME_MIN_LENGTH = 1;
export const CONTROLLER_HANDLER_ACTION_NAME_MAX_LENGTH = 45;
export const CONTROLLER_HANDLER_METHOD_NAME_MIN_LENGTH = 1;
export const CONTROLLER_HANDLER_METHOD_NAME_MAX_LENGTH = 45;
