[tool.poetry]
name = "dogu-device-client"
version = "0.1.0"
description = "dogutech's device client to control devices"
authors = ["Dogu Technologies"]
readme = "README.md"
packages = [{include = "dogu_device_client"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
