version: '3.7'

services:
  prod-dogu-docs:
    image: 910027912039.dkr.ecr.ap-northeast-2.amazonaws.com/prod-dogu-docs:latest
    pull_policy: always
    ports:
      - 3100:3100
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
