#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

echo [pre-commit] start

echo [validate-workspace] start
yarn node validate-workspace.mjs
echo [validate-workspace] end

echo [lint] start
yarn lint
echo [lint] end

echo [lint-staged] start
yarn lint-staged --allow-empty --config ./lint-staged.config.mjs
echo [lint-staged] end

echo [test] start
yarn test
echo [test] end

echo [pre-commit] end
