const resources = {
  icons: {
    volumeUp: '/resources/icons/volume-up.svg',
    volumeDown: '/resources/icons/volume-down.svg',
    volumeMute: '/resources/icons/volume-mute.svg',
    screenshot: '/resources/icons/screenshot.svg',
    keycap: '/resources/icons/keycap.svg',
    externalLink: '/resources/icons/external-link.svg',
    logo: '/resources/icons/logo.svg',
    xbox: '/resources/icons/xbox.svg',
    ps4: '/resources/icons/ps4.svg',
    linux: '/resources/icons/linux.svg',
    logoHorizontal: '/resources/icons/logo-horizontal.svg',
    googleLogo: '/resources/icons/g-logo.png',
    typescript: '/resources/icons/languages/typescript.svg',
    javascript: '/resources/icons/languages/javascript.svg',
    node: '/resources/icons/languages/node.svg',
    python: '/resources/icons/languages/python.svg',
    appium: '/resources/icons/frameworks/appium.png',
    gamium: '/resources/icons/frameworks/gamium.svg',
    webdriverio: '/resources/icons/frameworks/webdriverio.svg',
    jest: '/resources/icons/frameworks/jest.svg',
    pytest: '/resources/icons/frameworks/pytest.svg',
    selenium: '/resources/icons/frameworks/selenium.svg',
    studioLogo: '/resources/icons/studio-logo.svg',
    smilingFace: '/resources/icons/smiling-face.svg',
    neutralFace: '/resources/icons/neutral-face.svg',
    pensiveFace: '/resources/icons/pensive-face.svg',
    inactiveSmilingFace: '/resources/icons/inactive-smiling-face.svg',
    inactiveNeutralFace: '/resources/icons/inactive-neutral-face.svg',
    inactivePensiveFace: '/resources/icons/inactive-pensive-face.svg',
    chrome: '/resources/icons/browsers/chrome.svg',
    firefox: '/resources/icons/browsers/firefox.svg',
    safari: '/resources/icons/browsers/safari.svg',
    edge: '/resources/icons/browsers/edge.svg',
    samsungIntenet: '/resources/icons/browsers/samsung-internet.svg',
    reactNative: '/resources/icons/react-native.svg',
    mapMarker: '/resources/icons/map-marker.svg',
  },
  images: {},
};

export default resources;
