name: 🔄ci-sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        runner: [ubuntu-22.04, windows-2019, macos-latest]

    runs-on: ['${{ matrix.runner }}']
