name: 🔄e2e

on:
  push:
    branches: ['feature/deployment-process']
    paths:
      - '.github/workflows/e2e.yml'
      - 'dogu-actions/**'
      - 'e2e/**'
      - 'nm-space/**'
      - 'packages/**'
      - 'pipeline-samples/**'
      - 'prebuilds/**'
      - 'projects/**'
      - 'scripts/**'
      - '.pnp.cjs'
      - '.pnp.loader.mjs'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'
  pull_request:
    branches: ['feature/deployment-process']
    paths:
      - '.github/workflows/e2e.yml'
      - 'dogu-actions/**'
      - 'e2e/**'
      - 'nm-space/**'
      - 'packages/**'
      - 'pipeline-samples/**'
      - 'prebuilds/**'
      - 'projects/**'
      - 'scripts/**'
      - '.pnp.cjs'
      - '.pnp.loader.mjs'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'
  workflow_dispatch:

jobs:
  build-and-push-dogu-console:
    runs-on: e2e-dogu-build

    steps:
      - name: docker init
        run: docker system prune --volumes -a -f

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          no-cache: true
          context: .
          file: ./Dockerfile
          push: true
          target: dogu-console
          tags: |
            dogutechio/dogu-e2e:latest

  start-e2e-dogu:
    runs-on: e2e-dogu
    needs: build-and-push-dogu-console

    steps:
      - name: Checkout
        uses: Bhacaz/checkout-files@v2
        with:
          branch: ${{ github.ref_name  }}
          files: docker-compose.yml docker-compose.env

      - name: docker init
        run: docker system prune --volumes -a -f

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set .env
        run: |
          sed -i 's/dogu:latest/dogu-e2e:latest/' ./docker-compose.yml
          sed -i '/^  console:/a\    env_file:\n      - docker-compose.env' docker-compose.yml

          sed -i 's/^DOGU_HOST=.*$/DOGU_HOST=${{ secrets.E2E_DOGU_HOST }}/' ./docker-compose.env
          sed -i 's/^DEVICE_WIFI_SSID=.*$/DEVICE_WIFI_SSID=${{ secrets.DOGU_DEVICE_WIFI_SSID }}/' ./docker-compose.env
          sed -i 's/^DEVICE_WIFI_PASSWORD=.*$/DEVICE_WIFI_PASSWORD=${{ secrets.DOGU_DEVICE_WIFI_PASSWORD }}/' ./docker-compose.env
          sed -i 's/^GITLAB_ROOT_ACCESS_TOKEN=.*$/GITLAB_ROOT_ACCESS_TOKEN=${{ secrets.E2E_DOGU_GITLAB_ROOT_TOKEN }}/' ./docker-compose.env
          echo "DOGU_GITLAB_PORT=8080" >> ./docker-compose.env
          echo "DOGU_GITLAB_TEMPLATE_GROUP=dogu" >> ./docker-compose.env
          echo "DOGU_RUN_TYPE=e2e" >> ./docker-compose.env

      - name: run
        run: |
          docker compose -f ./docker-compose.yml stop console
          docker compose -f docker-compose.yml pull
          docker compose -f ./docker-compose.yml --env-file ./docker-compose.env up -d

  e2e:
    needs: start-e2e-dogu
    strategy:
      # max-parallel: 3
      fail-fast: false
      matrix:
        platform: [Windows, macOS]
        arch: [X64, ARM64]

        exclude:
          - platform: Windows
            arch: ARM64

    runs-on: [e2e, '${{ matrix.platform }}', '${{ matrix.arch }}']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: true

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Run newbie
        run: |
          yarn run newbie:cicd

      - name: Build Projects
        run: |
          yarn workspace dogu run build

      - name: Newbie nm-space
        run: |
          yarn workspace dogu run newbie:nm-space

      - name: Build nm-space
        run: |
          yarn workspace nm-space run build
        working-directory: ./nm-space

      - name: Windows - Powershell - Check
        if: runner.os == 'Windows'
        id: checkpowershell
        run: winget list Microsoft.PowerShell --accept-source-agreements
        continue-on-error: true

      - name: Windows - Powershell - Upgrade
        if: runner.os == 'Windows' && steps.checkpowershell.outcome == 'success'
        run: |
          winget install --id Microsoft.Powershell --source winget --silent
        continue-on-error: true

      - name: Windows - Powershell - Add to Env
        if: runner.os == 'Windows'
        run: |
          "C:\Program Files\PowerShell\7" >> $env:GITHUB_PATH

      - name: Windows - Msys2 - MIGW64 - Setup for cgo
        uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          msystem: MINGW64
          location: ${{ github.workspace }}
          install: >-
            git
            base-devel
            mingw-w64-x86_64-gcc

      - name: Windows - Setup Cmake
        if: runner.os == 'Windows'
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.25.1
          ninjaVersion: 1.11.1

      - name: Macos - Setup Cmake,
        if: runner.os == 'macOS'
        run: brew install cmake
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        continue-on-error: true

      - name: Common - Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'

      - name: Common - Set up JDK 11 for android build
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Common - Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: create dotEnv
        run: |
          env-generator gen-all e2e

      - name: Download, Build third-party
        run: |
          yarn third-party:download:build

      - name: Run e2e
        if: ${{ success() }}
        run: |
          yarn workspace e2e run util:install-chromedriver && yarn workspace e2e run start:ci

      - name: Upload video
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: 'e2e-${{ matrix.platform }}-${{ matrix.arch }}'
          path: |
            ./e2e/generated/record/screen-${{ runner.os }}-${{github.sha}}.webm

  send-slack:
    runs-on: ubuntu-latest
    needs: e2e
    if: ${{ always() }}

    steps:
      - name: Send Slack
        uses: dogu-team/slack@v1.0
        with:
          template: 'e2e'
          slack-channel-id: 'C03PL9TC44Q'
          result-status: ${{ needs.e2e.result }}
          ignore-notify: ${{ needs.e2e.result == 'success' }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
