name: 🚀release-gcp
run-name: 🚀release-gcp-${{github.event.inputs.run_type}}-${{github.event.inputs.project_type}}@${{github.ref_name}}

on:
  workflow_dispatch:
    inputs:
      run_type:
        type: choice
        description: Select run type
        options:
          - development
          - production

      project_type:
        type: choice
        description: Select project type
        options:
          - console-web-front
          - console-web-server

permissions:
  id-token: write
  contents: read

env:
  DOGU_GCP_REGION: asia-northeast3

jobs:
  parse-inputs:
    runs-on: ubuntu-latest
    env:
      RED: '\033[0;31m'
      GREEN: '\033[0;32m'
      NC: '\033[0m'
      DEV_DOGU_DOCKER_TAG: asia-northeast3-docker.pkg.dev/${{secrets.GCP_DEV_PROJECT_ID}}/projects/${{github.event.inputs.project_type}}:${{github.ref_name}}
      PROD_DOGU_DOCKER_TAG: asia-northeast3-docker.pkg.dev/${{secrets.GCP_PROD_PROJECT_ID}}/projects/${{github.event.inputs.project_type}}:${{github.ref_name}}
      GCP_DEV_CICD_SA_KEY: ${{secrets.GCP_DEV_CICD_SA_KEY}}
      GCP_PROD_CICD_SA_KEY: ${{secrets.GCP_PROD_CICD_SA_KEY}}
      GCP_DEV_PRIVATE_SSH_KEY: ${{secrets.GCP_DEV_PRIVATE_SSH_KEY}}
      GCP_PROD_PRIVATE_SSH_KEY: ${{secrets.GCP_PROD_PRIVATE_SSH_KEY}}
      DOGU_RUN_TYPE: ${{github.event.inputs.run_type}}
      DOGU_PROJECT_TYPE: ${{github.event.inputs.project_type}}
    outputs:
      gcp-sa-key: ${{steps.parse-gcp-sa-key.outputs.gcp-sa-key}}
      gcp-private-ssh-key: ${{steps.parse-gcp-private-ssh-key.outputs.gcp-private-ssh-key}}
      docker-tag: ${{steps.parse-docker-tag.outputs.docker-tag}}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Validate inputs
        run: |
          echo "
            const validRunType = ['evelopment', 'production'];
            const validProjectType = ['console-web-front', 'console-web-server'];
            if (!validRunType.includes('${{github.event.inputs.run_type}}')) {
              throw new Error('run_type is not valid');
            }

            if (!validProjectType.includes('${{github.event.inputs.project_type}}')) {
              throw new Error('project_type is not valid');
            }
          " > validate.mjs
          node validate.mjs

      - id: parse-gcp-sa-key
        name: Parse GCP SA Key
        run: |
          if [ "${{github.event.inputs.run_type}}" = "development" ]; then
            echo "gcp-sa-key<<EOF" >> "$GITHUB_OUTPUT"
            echo "$GCP_DEV_CICD_SA_KEY" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"

          elif [ "${{github.event.inputs.run_type}}" = "production" ]; then
            echo "gcp-sa-key<<EOF" >> "$GITHUB_OUTPUT"
            echo "$GCP_PROD_CICD_SA_KEY" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"

          else
            echo -e "${RED}run_type is not valid${NC}"
            exit 1
          fi

      - id: parse-gcp-private-ssh-key
        name: Parse GCP Private SSH Key
        run: |
          if [ "${{github.event.inputs.run_type}}" = "development" ]; then
            echo "gcp-private-ssh-key<<EOF" >> "$GITHUB_OUTPUT"
            echo "$GCP_DEV_PRIVATE_SSH_KEY" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"

          elif [ "${{github.event.inputs.run_type}}" = "production" ]; then
            echo "gcp-private-ssh-key<<EOF" >> "$GITHUB_OUTPUT"
            echo "$GCP_PROD_PRIVATE_SSH_KEY" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"

          else
            echo -e "${RED}run_type is not valid${NC}"
            exit 1
          fi

      - id: parse-docker-tag
        name: Parse docker-tag
        run: |
          if [ "${{github.event.inputs.run_type}}" = "development" ]; then
            echo "docker-tag=$DEV_DOGU_DOCKER_TAG" >> "$GITHUB_OUTPUT"

          elif [ "${{github.event.inputs.run_type}}" = "production" ]; then
            echo "docker-tag=$PROD_DOGU_DOCKER_TAG" >> "$GITHUB_OUTPUT"

          else
            echo -e "${RED}run_type is not valid${NC}"
            exit 1
          fi

  publish:
    needs: parse-inputs
    runs-on: henry-macbook

    steps:
      - name: Print inputs
        run: |
          echo "$GCP_CICD_SA_KEY" > $HOME/1.txt
          echo "$GCP_PRIVATE_SSH_KEY" > $HOME/2.txt
          echo "$DOCKER_TAG" > $HOME/3.txt
        env:
          GCP_CICD_SA_KEY: ${{needs.parse-inputs.outputs.gcp-sa-key}}
          GCP_PRIVATE_SSH_KEY: ${{needs.parse-inputs.outputs.gcp-private-ssh-key}}
          DOCKER_TAG: ${{needs.parse-inputs.outputs.docker-tag}}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Yarn Unplugged
        uses: actions/cache@v3
        id: cache_yarn_unplugged
        env:
          cache-name: cache-yarn-unplugged
        with:
          path: ${{github.workspace}}/.yarn/unplugged
          key: ${{runner.os}}-${{env.cache-name}}-${{hashFiles('yarn.lock')}}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - id: auth
        name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: access_token
          credentials_json: '${{env.GCP_CICD_SA_KEY}}'
          access_token_lifetime: 300s
        env:
          GCP_CICD_SA_KEY: ${{needs.parse-inputs.outputs.gcp-sa-key}}

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{env.DOGU_GCP_REGION}}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{steps.auth.outputs.access_token}}

      - name: Push to Artifact Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{needs.parse-inputs.outputs.docker-tag}}
          file: dockerfile.gcp
          build-args: DOGU_RUN_TYPE=${{github.event.inputs.run_type}}
          target: ${{github.event.inputs.project_type}}

  release:
    runs-on: ubuntu-latest
    needs:
      - parse-inputs
      - publish

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: docker-compose-gcp.yml

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{needs.parse-inputs.outputs.gcp-sa-key}}'

      - name: Rlease to Google Cloud Compute Engine
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: ${{github.event.inputs.project_type}}
          zone: ${{env.DOGU_GCP_REGION}}-a
          ssh_private_key: '${{needs.parse-inputs.outputs.gcp-private-ssh-key}}'
          command: |
            gcloud auth configure-docker ${{env.DOGU_GCP_REGION}}-docker.pkg.dev --quiet && \
            docker ps -qa | xargs -r docker rm -f && \
            docker system prune --volumes -a -f && \
            docker pull ${{needs.parse-inputs.outputs.docker-tag}} && \
            DOGU_DOCKER_TAG=${{needs.parse-inputs.outputs.docker-tag}} docker compose -f docker-compose-gcp.yml --verbose up -d ${{github.event.inputs.project_type}} && \
            docker image prune -a -f

  send-slack:
    runs-on: ubuntu-latest
    needs: release
    if: ${{always()}}

    steps:
      - name: Send Slack
        uses: dogu-team/slack@v1.0
        with:
          template: 'CD'
          slack-channel-id: 'C057ML9UH34'
          result-status: ${{needs.release.result}}
          ignore-notify: false
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
