name: 🚀release-self-hosted

on:
  workflow_dispatch:
    inputs:
      gitpat:
        type: string
        description: 'gitlab root token'
        default: 'gitpat'

jobs:
  # build-and-push-dogu-console:
  #   runs-on: dogu-self-hosted
  #   steps:
  #     - name: docker init
  #       run: docker system prune --volumes -a -f

  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: .
  #         file: ./Dockerfile
  #         push: true
  #         target: dogu-console
  #         tags: |
  #           dogutechio/dogu:rc

  start-rc-dogu:
    runs-on: dogu-self-hosted
    # needs: build-and-push-dogu-console

    steps:
      - name: Checkout
        uses: Bhacaz/checkout-files@v2
        with:
          files: docker-compose.yml docker-compose.env

      - name: docker init
        run: docker system prune --volumes -a -f

      - name: set .env
        run: |
          sed -i 's/^DOGU_HOST=.*$/DOGU_HOST=dev.dogutech.io/' ./docker-compose.env

          # postgres
          echo "DOGU_RDS_HOST=${{ secrets.DEV_DOGU_RDS_HOST }}" >> ./docker-compose.env
          sed -i 's/^POSTGRES_USER=.*$/POSTGRES_USER=${{ secrets.DEV_DOGU_RDS_USERNAME }}/' ./docker-compose.env
          sed -i 's/^POSTGRES_PASSWORD=.*$/POSTGRES_PASSWORD=${{ secrets.DEV_DOGU_RDS_PASSWORD }}/' ./docker-compose.env

          # influxdb
          sed -i 's/^INFLUX_DB_INIT_ADMIN_TOKEN=.*$/INFLUX_DB_INIT_ADMIN_TOKEN=${{ secrets.DEV_DOGU_INFLUX_DB_TOKEN }}/' ./docker-compose.env
          sed -i 's/^INFLUX_DB_USERNAME=.*$/INFLUX_DB_USERNAME=${{ secrets.DEV_DOGU_INFLUX_DB_USERNAME }}/' ./docker-compose.env
          sed -i 's/^INFLUX_DB_PASSWORD=.*$/INFLUX_DB_PASSWORD=${{ secrets.DEV_DOGU_INFLUX_DB_PASSWORD }}/' ./docker-compose.env

          # redis
          sed -i 's/^REDIS_PASSWORD=.*$/REDIS_PASSWORD=${{ secrets.DEV_DOGU_REDIS_PASSWORD }}/' ./docker-compose.env

          # console
          sed -i 's/^GITLAB_ROOT_ACCESS_TOKEN=.*$/GITLAB_ROOT_ACCESS_TOKEN=${{ github.event.inputs.gitpat }}/' ./docker-compose.env
          sed -i 's/^GITLAB_ROOT_PASSWORD=.*$/GITLAB_ROOT_PASSWORD=${{ secrets.DEV_DOGU_GITLAB_ROOT_PASSWORD }}/' ./docker-compose.env
          sed -i 's/^DOGU_CONSOLE_JWT_SECRET_KEY=.*$/DOGU_CONSOLE_JWT_SECRET_KEY=${{ secrets.DEV_DOGU_JWT_SECRET_KEY }}/' ./docker-compose.env
          sed -i 's/^DEVICE_WIFI_SSID=.*$/DEVICE_WIFI_SSID=${{ secrets.DEV_DOGU_DEVICE_WIFI_SSID }}/' ./docker-compose.env
          sed -i 's/^DEVICE_WIFI_PASSWORD=.*$/DEVICE_WIFI_PASSWORD=${{ secrets.DEV_DOGU_DEVICE_WIFI_PASSWORD }}/' ./docker-compose.env

          echo "DOGU_CONSOLE_URL=https://console.${DOGU_HOST}" >> ./docker-compose.env
          echo "DOGU_EMAIL_ID=${{ secrets.DOGU_EMAIL_ID }}" >> ./docker-compose.env
          echo "DOGU_EMAIL_PW=${{ secrets.DOGU_EMAIL_PW }}" >> ./docker-compose.env
          echo "DOGU_DOST_DOWNLOAD_BASE_URL=${{ secrets.DOGU_DOST_DOWNLOAD_BASE_URL }}" >> ./docker-compose.env
          echo "DOGU_RECAPTCHA_KEY=${{ secrets.DOGU_RECAPTCHA_KEY }}" >> ./docker-compose.env
          echo "DOGU_CONSOLE_GOOGLE_OAUTH_LOGIN_CLIENT_ID=${{ secrets.DOGU_CONSOLE_GOOGLE_OAUTH_LOGIN_CLIENT_ID }}" >> ./docker-compose.env
          echo "DOGU_CONSOLE_GOOGLE_OAUTH_LOGIN_CLIENT_SECRET=${{ secrets.DOGU_CONSOLE_GOOGLE_OAUTH_LOGIN_CLIENT_SECRET }}" >> ./docker-compose.env
          echo "DOGU_GITLAB_HOST=gitlab.dev.dogutech.io" >> ./docker-compose.env
          echo "DOGU_GITLAB_PORT=443" >> ./docker-compose.env
          echo "DOGU_GITLAB_PROTOCOL=https" >> ./docker-compose.env
          echo "DOGU_GITLAB_TEMPLATE_GROUP=dogu" >> ./docker-compose.env

          # file server
          sed -i 's/^FILE_SERVER_USERNAME=.*$/FILE_SERVER_USERNAME=${{ secrets.DEV_DOGU_FILE_SERVER_USERNAME }}/' ./docker-compose.env
          sed -i 's/^FILE_SERVER_PASSWORD=.*$/FILE_SERVER_PASSWORD=${{ secrets.DEV_DOGU_FILE_SERVER_PASSWORD }}/' ./docker-compose.env

          # turn server
          sed -i 's/^TURN_SERVER_USERNAME=.*$/TURN_SERVER_USERNAME=${{ secrets.DEV_DOGU_TURN_SERVER_USERNAME }}/' ./docker-compose.env
          sed -i 's/^TURN_SERVER_PASSWORD=.*$/TURN_SERVER_PASSWORD=${{ secrets.DEV_DOGU_TURN_SERVER_PASSWORD }}/' ./docker-compose.env

      - name: run dogu
        run: |
          docker compose -f ./docker-compose.yml --env-file ././docker-compose.env up -d --scale postgres=0
