name: 🚀release-npm-and-actions

on:
  workflow_dispatch:

env:
  DOGU_DEPLOY: true
  DOGU_PYTHON_VERSION: 3.9.13
  DOGU_POETRY_VERSION: 1.5.1

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python & Poetry
        uses: gabrielfalcao/pyenv-action@v11
        with:
          default: ${{ env.DOGU_PYTHON_VERSION }}
          command: pyenv global ${{ env.DOGU_PYTHON_VERSION }} && pip install poetry==${{ env.DOGU_POETRY_VERSION }} && which poetry

      - name: Run newbie
        run: |
          yarn newbie:cicd

      - name: Build packages
        run: |
          yarn build:packages

      - name: Build dogu-actions
        run: |
          yarn build:actions

      - name: Publish to npm
        run: |
          yarn publish:npm:prod

      - name: Publish to github dogu-actions
        run: |
          yarn publish:github:prod

  send-slack:
    runs-on: ubuntu-latest
    needs: publish
    if: ${{ always() }}

    steps:
      - name: Send Slack
        uses: dogu-team/slack@v1.0
        with:
          template: 'CD'
          slack-channel-id: 'C03PL9TC44Q'
          result-status: ${{ needs.publish.result }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
