name: 🚀release-gcp
run-name: 🚀release-gcp-${{github.event.inputs.run_type}}-${{github.event.inputs.project_type}}@${{github.ref_name}}

on:
  workflow_dispatch:
    inputs:
      run_type:
        type: choice
        description: Select run type
        options:
          - development
          - production

      project_type:
        type: choice
        description: Select project type
        options:
          - console-web-front
          - console-web-server

permissions:
  id-token: write
  contents: read

env:
  DOGU_GCP_REGION: asia-northeast3
  DEV_DOGU_DOCKER_TAG: asia-northeast3-docker.pkg.dev/${{secrets.GCP_DEV_PROJECT_ID}}/projects/${{github.event.inputs.project_type}}:${{github.ref_name}}
  PROD_DOGU_DOCKER_TAG: asia-northeast3-docker.pkg.dev/${{secrets.GCP_PROD_PROJECT_ID}}/projects/${{github.event.inputs.project_type}}:${{github.ref_name}}
  RED: '\033[0;31m'
  GREEN: '\033[0;32m'
  NC: '\033[0m'

  # for echo multi-line string to file
  GCP_DEV_PRIVATE_SSH_KEY: ${{secrets.GCP_DEV_PRIVATE_SSH_KEY}}
  GCP_PROD_PRIVATE_SSH_KEY: ${{secrets.GCP_PROD_PRIVATE_SSH_KEY}}
  GCP_DEV_CICD_SA_KEY: ${{secrets.GCP_DEV_CICD_SA_KEY}}
  GCP_PROD_CICD_SA_KEY: ${{secrets.GCP_PROD_CICD_SA_KEY}}

jobs:
  parse-inputs:
    runs-on: henry-macbook
    outputs:
      gcp_cicd_sa_key: ${{steps.parse_gcp_cicd_sa_key.outputs.gcp_cicd_sa_key}}
      gcp_private_ssh_key: ${{steps.parse_gcp_private_ssh_key.outputs.gcp_private_ssh_key}}
      docker_tag: ${{steps.parse_docker_tag.outputs.docker_tag}}
    steps:
      - name: Print inputs
        run: |
          echo "$GCP_DEV_CICD_SA_KEY" > $HOME/gcp_dev_cicd_sa_key.json
          echo "$GCP_DEV_PRIVATE_SSH_KEY" > $HOME/gcp_dev_private_ssh_key

      - name: Validate inputs
        run: |
          if [ "${{github.event.inputs.run_type}}" != "development" ] &&
            [ "${{github.event.inputs.run_type}}" != "production" ]; then
            echo -e "${RED}run_type is not valid${NC}"
            exit 1
          fi

          if [ "${{github.event.inputs.project_type}}" != "console-web-front" ] &&
            [ "${{github.event.inputs.project_type}}" != "console-web-server" ]; then
            echo -e "${RED}project_type is not valid${NC}"
            exit 1
          fi

      - id: parse_gcp_cicd_sa_key
        name: Parse gcp_cicd_sa_key
        run: |
          if [ "${{github.event.inputs.run_type}}" = "development" ]; then
            printf "gcp_cicd_sa_key<<EOF\n%s\nEOF\n" "$GCP_DEV_CICD_SA_KEY" >> $GITHUB_OUTPUT

          elif [ "${{github.event.inputs.run_type}}" = "production" ]; then
            printf "gcp_cicd_sa_key<<EOF\n%s\nEOF\n" "$GCP_PROD_CICD_SA_KEY" >> $GITHUB_OUTPUT

          else
            echo -e "${RED}run_type is not valid${NC}"
            exit 1
          fi

      - id: parse_gcp_private_ssh_key
        name: Parse gcp_private_ssh_key
        run: |
          if [ "${{github.event.inputs.run_type}}" = "development" ]; then
            printf "gcp_private_ssh_key<<EOF\n%s\nEOF\n" "$GCP_DEV_PRIVATE_SSH_KEY" >> $GITHUB_OUTPUT

          elif [ "${{github.event.inputs.run_type}}" = "production" ]; then
            printf "gcp_private_ssh_key<<EOF\n%s\nEOF\n" "$GCP_PROD_PRIVATE_SSH_KEY" >> $GITHUB_OUTPUT

          else
            echo -e "${RED}run_type is not valid${NC}"
            exit 1
          fi

      - id: parse_docker_tag
        name: Parse docker_tag
        run: |
          if [ "${{github.event.inputs.run_type}}" = "development" ]; then
            echo "docker_tag=$DEV_DOGU_DOCKER_TAG" >> $GITHUB_OUTPUT

          elif [ "${{github.event.inputs.run_type}}" = "production" ]; then
            echo "docker_tag=$PROD_DOGU_DOCKER_TAG" >> $GITHUB_OUTPUT

          else
            echo -e "${RED}run_type is not valid${NC}"
            exit 1
          fi

  publish:
    needs: parse-inputs
    runs-on: ubuntu-latest

    steps:
      - name: Print inputs
        run: |
          echo "$GCP_CICD_SA_KEY" > $HOME/gcp_cicd_sa_key.json
          echo "$GCP_PRIVATE_SSH_KEY" > $HOME/gcp_private_ssh_key
          echo "$DOCKER_TAG" > $HOME/docker_tag
        env:
          GCP_CICD_SA_KEY: ${{needs.parse-inputs.outputs.gcp_cicd_sa_key}}
          GCP_PRIVATE_SSH_KEY: ${{needs.parse-inputs.outputs.gcp_private_ssh_key}}
          DOCKER_TAG: ${{needs.parse-inputs.outputs.docker_tag}}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Yarn Unplugged
        uses: actions/cache@v3
        id: cache_yarn_unplugged
        env:
          cache-name: cache-yarn-unplugged
        with:
          path: ${{github.workspace}}/.yarn/unplugged
          key: ${{runner.os}}-${{env.cache-name}}-${{hashFiles('yarn.lock')}}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - id: auth
        name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: access_token
          credentials_json: '${{env.GCP_CICD_SA_KEY}}'
          access_token_lifetime: 300s
        env:
          GCP_CICD_SA_KEY: ${{needs.parse-inputs.outputs.gcp_cicd_sa_key}}

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{env.DOGU_GCP_REGION}}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{steps.auth.outputs.access_token}}

      - name: Push to Artifact Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{needs.parse-inputs.outputs.docker_tag}}
          file: dockerfile.gcp
          build-args: DOGU_RUN_TYPE=${{github.event.inputs.run_type}}
          target: ${{github.event.inputs.project_type}}

  release:
    runs-on: ubuntu-latest
    needs:
      - parse-inputs
      - publish

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: docker-compose-gcp.yml

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{needs.parse-inputs.outputs.gcp_cicd_sa_key}}'

      - name: Rlease to Google Cloud Compute Engine
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: ${{github.event.inputs.project_type}}
          zone: ${{env.DOGU_GCP_REGION}}-a
          ssh_private_key: '${{needs.parse-inputs.outputs.gcp_private_ssh_key}}'
          command: |
            gcloud auth configure-docker ${{env.DOGU_GCP_REGION}}-docker.pkg.dev --quiet && \
            docker ps -qa | xargs -r docker rm -f && \
            docker system prune --volumes -a -f && \
            docker pull ${{needs.parse-inputs.outputs.docker_tag}} && \
            DOGU_DOCKER_TAG=${{needs.parse-inputs.outputs.docker_tag}} docker compose -f docker-compose-gcp.yml --verbose up -d ${{github.event.inputs.project_type}} && \
            docker image prune -a -f

  send-slack:
    runs-on: ubuntu-latest
    needs: release
    if: ${{always()}}

    steps:
      - name: Send Slack
        uses: dogu-team/slack@v1.0
        with:
          template: 'CD'
          slack-channel-id: 'C057ML9UH34'
          result-status: ${{needs.release.result}}
          ignore-notify: false
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
