name: 🚀release-e2e-dogu

on:
  workflow_dispatch:

jobs:
  build-and-push-dogu-console:
    runs-on: e2e-dogu-build

    steps:
      - name: docker init
        run: docker system prune --volumes -a -f

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: dogu-console
          tags: |
            dogutechio/dogu-e2e:latest

  start-e2e-dogu:
    runs-on: e2e-dogu
    needs: build-and-push-dogu-console

    steps:
      - name: Checkout
        uses: Bhacaz/checkout-files@v2
        with:
          branch: ${{ github.ref_name  }}
          files: docker-compose.yml docker-compose.env

      - name: docker init
        run: docker system prune --volumes -a -f

      - name: set .env
        run: |
          sed -i 's/dogu:latest/dogu-e2e:latest/' ./docker-compose.yml
          sed -i 's/^DOGU_HOST=.*$/DOGU_HOST=${{ secrets.E2E_DOGU_HOST }}/' ./docker-compose.env
          sed -i 's/^DEVICE_WIFI_SSID=.*$/DEVICE_WIFI_SSID=${{ secrets.DOGU_DEVICE_WIFI_SSID }}/' ./docker-compose.env
          sed -i 's/^DEVICE_WIFI_PASSWORD=.*$/DEVICE_WIFI_PASSWORD=${{ secrets.DOGU_DEVICE_WIFI_PASSWORD }}/' ./docker-compose.env
          sed -i 's/^GITLAB_ROOT_ACCESS_TOKEN=.*$/GITLAB_ROOT_ACCESS_TOKEN=${{ secrets.E2E_DOGU_GITLAB_ROOT_TOKEN }}/' ./docker-compose.env

      - name: run
        run: |
          docker compose -f ./docker-compose.yml --env-file ./docker-compose.env up -d
