name: 🧪🚀test-release-dogu-agent-cli

on:
  workflow_dispatch:
    inputs:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.TEST_GOOGLE_CLOUD_ARTIFACT_REGISTRY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure Docker Client of Gcloud
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./dockerfile
          target: dogu-agent
          platforms: linux/amd64
          no-cache: true
          push: true
          tags: asia-northeast3-docker.pkg.dev/dogu-project-379607/test-dogu-agent-cli:latest

  send-slack:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ always() }}

    steps:
      - name: Send Slack
        uses: dogu-team/slack@v1.0
        with:
          template: 'CD'
          slack-channel-id: 'C057ML9UH34'
          result-status: ${{ needs.build-and-push.result }}
          ignore-notify: false
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
