//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreFoundation/CoreFoundation.h>
#import <Foundation/Foundation.h>

@interface XCSymbolicatorHolder : NSObject
{
    struct _CSTypeRef _symbolicator;
}

@property struct _CSTypeRef symbolicator; // @synthesize symbolicator=_symbolicator;

@end
